# Don't forget to run 
# `docker compose up` with `ENVIRONMENT=base` set in `.env`
# the first time you run this project!"

services:
  app:
    container_name: "Spring-boot-${ENVIRONMENT}"
    build:
      context: .
      dockerfile: Dockerfile
      target: "${ENVIRONMENT}" # Use the environment variable to target the desired stage
    environment:
      # Pass environment variables to the container and the Spring Boot app
      SPRING_PROFILES_ACTIVE: "${ENVIRONMENT}"
      PORT: "${PORT}"
      # Declare the production database in `application.proprieties` to prevent
      # pushing to github the URL by mistake 
      # SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
      DEV_SPRING_DATASOURCE_URL: "${DEV_SPRING_DATASOURCE_URL}"
      TEST_SPRING_DATASOURCE_URL: "${TEST_SPRING_DATASOURCE_URL}"
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    networks:
      - spring_network

  db:
    container_name: "Spring-boot-mariadb"
    # TODO: Find a lightweight LTS docker image for mariadb
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: "pwd"
      MARIADB_DATABASE: "dev_db"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring_network

networks:
  spring_network:
    driver: bridge
