# Tomcat configuration
server.port=${PORT:8080}

# Log level configuration
logging.level.root=ERROR
logging.level.ch.sectioninformatique=ERROR
logging.level.org.springframework.boot.web.embedded.tomcat=ERROR
