# Log level configuration
logging.level.root=ERROR
logging.level.ch.sectioninformatique=INFO
logging.level.org.springframework.boot.web.embedded.tomcat=INFO

# Show SQL in stdout and stderr
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Change how hibernate deals with database's Entity

spring.jpa.hibernate.ddl-auto=update
# MOCKED Database connection

# WARN: Be careful not to use the real database connection
# Use either a local database or the test database

# Handled by docker-compose `db` service
spring.datasource.url=${TEST_SPRING_DATASOURCE_URL}
